username: mingj
baseurl: /StrayBirds
markdown: redcarpet
safe: false
highlighter: pygments
title: jeiao's life 
description: In me the tiger sniffs the rose
theme: minimal
disqusname: mingj

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
